name: Trigger dockerCopilot workflow

on:
  push:
    branches:
      - master   # React 仓库主分支

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger dockerCopilot docker-build-push-latest
        env:
          GH_TOKEN: ${{ secrets.DOCKER_COPILOT_TRIGGER_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            https://api.github.com/repos/onlyLTY/dockerCopilot/actions/workflows/docker-build-push-latest.yml/dispatches \
            -d '{
              "ref": "latest"
            }'
